//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceClientApp.HumanResourceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="HumanResourceServiceReference.HumanResourceXmlWebService")]
    public interface HumanResourceXmlWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HumanResourceClientApp.HumanResourceServiceReference.findAllJobsResponse findAllJobs(HumanResourceClientApp.HumanResourceServiceReference.findAllJobs request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.findAllJobsResponse> findAllJobsAsync(HumanResourceClientApp.HumanResourceServiceReference.findAllJobs request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumberResponse luckyLottoNumber(HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumber request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumberResponse> luckyLottoNumberAsync(HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumber request);
        
        // CODEGEN: Parameter 'Job' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Job")]
        HumanResourceClientApp.HumanResourceServiceReference.findOneJobResponse findOneJob(HumanResourceClientApp.HumanResourceServiceReference.findOneJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.findOneJobResponse> findOneJobAsync(HumanResourceClientApp.HumanResourceServiceReference.findOneJob request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HumanResourceClientApp.HumanResourceServiceReference.luckyNumbersResponse luckyNumbers(HumanResourceClientApp.HumanResourceServiceReference.luckyNumbers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.luckyNumbersResponse> luckyNumbersAsync(HumanResourceClientApp.HumanResourceServiceReference.luckyNumbers request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
    public partial class job : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jobIdField;
        
        private string jobTitleField;
        
        private decimal maxSalaryField;
        
        private bool maxSalaryFieldSpecified;
        
        private decimal minSalaryField;
        
        private bool minSalaryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("jobId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string jobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
                this.RaisePropertyChanged("jobTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal maxSalary {
            get {
                return this.maxSalaryField;
            }
            set {
                this.maxSalaryField = value;
                this.RaisePropertyChanged("maxSalary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSalarySpecified {
            get {
                return this.maxSalaryFieldSpecified;
            }
            set {
                this.maxSalaryFieldSpecified = value;
                this.RaisePropertyChanged("maxSalarySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal minSalary {
            get {
                return this.minSalaryField;
            }
            set {
                this.minSalaryField = value;
                this.RaisePropertyChanged("minSalary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minSalarySpecified {
            get {
                return this.minSalaryFieldSpecified;
            }
            set {
                this.minSalaryFieldSpecified = value;
                this.RaisePropertyChanged("minSalarySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllJobs", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class findAllJobs {
        
        public findAllJobs() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllJobsResponse", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class findAllJobsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HumanResourceClientApp.HumanResourceServiceReference.job[] @return;
        
        public findAllJobsResponse() {
        }
        
        public findAllJobsResponse(HumanResourceClientApp.HumanResourceServiceReference.job[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luckyLottoNumber", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class luckyLottoNumber {
        
        public luckyLottoNumber() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luckyLottoNumberResponse", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class luckyLottoNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public luckyLottoNumberResponse() {
        }
        
        public luckyLottoNumberResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findOneJob", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class findOneJob {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobId;
        
        public findOneJob() {
        }
        
        public findOneJob(string jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findOneJobResponse", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class findOneJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HumanResourceClientApp.HumanResourceServiceReference.job Job;
        
        public findOneJobResponse() {
        }
        
        public findOneJobResponse(HumanResourceClientApp.HumanResourceServiceReference.job Job) {
            this.Job = Job;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luckyNumbers", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class luckyNumbers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public luckyNumbers() {
        }
        
        public luckyNumbers(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luckyNumbersResponse", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class luckyNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public luckyNumbersResponse() {
        }
        
        public luckyNumbersResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HumanResourceXmlWebServiceChannel : HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HumanResourceXmlWebServiceClient : System.ServiceModel.ClientBase<HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService>, HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService {
        
        public HumanResourceXmlWebServiceClient() {
        }
        
        public HumanResourceXmlWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HumanResourceXmlWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanResourceXmlWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanResourceXmlWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanResourceClientApp.HumanResourceServiceReference.findAllJobsResponse HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService.findAllJobs(HumanResourceClientApp.HumanResourceServiceReference.findAllJobs request) {
            return base.Channel.findAllJobs(request);
        }
        
        public HumanResourceClientApp.HumanResourceServiceReference.job[] findAllJobs() {
            HumanResourceClientApp.HumanResourceServiceReference.findAllJobs inValue = new HumanResourceClientApp.HumanResourceServiceReference.findAllJobs();
            HumanResourceClientApp.HumanResourceServiceReference.findAllJobsResponse retVal = ((HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService)(this)).findAllJobs(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.findAllJobsResponse> HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService.findAllJobsAsync(HumanResourceClientApp.HumanResourceServiceReference.findAllJobs request) {
            return base.Channel.findAllJobsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.findAllJobsResponse> findAllJobsAsync() {
            HumanResourceClientApp.HumanResourceServiceReference.findAllJobs inValue = new HumanResourceClientApp.HumanResourceServiceReference.findAllJobs();
            return ((HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService)(this)).findAllJobsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumberResponse HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService.luckyLottoNumber(HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumber request) {
            return base.Channel.luckyLottoNumber(request);
        }
        
        public int luckyLottoNumber() {
            HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumber inValue = new HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumber();
            HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumberResponse retVal = ((HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService)(this)).luckyLottoNumber(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumberResponse> HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService.luckyLottoNumberAsync(HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumber request) {
            return base.Channel.luckyLottoNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumberResponse> luckyLottoNumberAsync() {
            HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumber inValue = new HumanResourceClientApp.HumanResourceServiceReference.luckyLottoNumber();
            return ((HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService)(this)).luckyLottoNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanResourceClientApp.HumanResourceServiceReference.findOneJobResponse HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService.findOneJob(HumanResourceClientApp.HumanResourceServiceReference.findOneJob request) {
            return base.Channel.findOneJob(request);
        }
        
        public HumanResourceClientApp.HumanResourceServiceReference.job findOneJob(string jobId) {
            HumanResourceClientApp.HumanResourceServiceReference.findOneJob inValue = new HumanResourceClientApp.HumanResourceServiceReference.findOneJob();
            inValue.jobId = jobId;
            HumanResourceClientApp.HumanResourceServiceReference.findOneJobResponse retVal = ((HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService)(this)).findOneJob(inValue);
            return retVal.Job;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.findOneJobResponse> HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService.findOneJobAsync(HumanResourceClientApp.HumanResourceServiceReference.findOneJob request) {
            return base.Channel.findOneJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.findOneJobResponse> findOneJobAsync(string jobId) {
            HumanResourceClientApp.HumanResourceServiceReference.findOneJob inValue = new HumanResourceClientApp.HumanResourceServiceReference.findOneJob();
            inValue.jobId = jobId;
            return ((HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService)(this)).findOneJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HumanResourceClientApp.HumanResourceServiceReference.luckyNumbersResponse HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService.luckyNumbers(HumanResourceClientApp.HumanResourceServiceReference.luckyNumbers request) {
            return base.Channel.luckyNumbers(request);
        }
        
        public string luckyNumbers(int arg0) {
            HumanResourceClientApp.HumanResourceServiceReference.luckyNumbers inValue = new HumanResourceClientApp.HumanResourceServiceReference.luckyNumbers();
            inValue.arg0 = arg0;
            HumanResourceClientApp.HumanResourceServiceReference.luckyNumbersResponse retVal = ((HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService)(this)).luckyNumbers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.luckyNumbersResponse> HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService.luckyNumbersAsync(HumanResourceClientApp.HumanResourceServiceReference.luckyNumbers request) {
            return base.Channel.luckyNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<HumanResourceClientApp.HumanResourceServiceReference.luckyNumbersResponse> luckyNumbersAsync(int arg0) {
            HumanResourceClientApp.HumanResourceServiceReference.luckyNumbers inValue = new HumanResourceClientApp.HumanResourceServiceReference.luckyNumbers();
            inValue.arg0 = arg0;
            return ((HumanResourceClientApp.HumanResourceServiceReference.HumanResourceXmlWebService)(this)).luckyNumbersAsync(inValue);
        }
    }
}
